5w2h.md
- Documento com 7 perguntas específicas sobre o projeto.
- [Feature] Elaboração do documento 5w2h
=> Criacao do documento 5w2h

5w2h.md, instrospeccao.md
- Documento com alguns requisitos elicitados pela perspectiva do usuário.
Exemplo :
- [Feature] Elaboração do documento de introspecção.
=> 35 introspeccao

docs/prototipoBaixa.md, docs/prototipoMedia.md, mkdocs.yml
https://github.com/UnBArqDsw2021-2/2021.2_G2_lava-jato/issues/27
- Adição do figma no documento
- Correção das refêrencias do protótipo de baixa fidelidade
=> [Feature] Adição documento protótipo de média fidelidade

docs/especificacaoSuplementar.md, docs/modelagem/Epicos/EP01.md, docs/modelagem/Epicos/EP02.md, docs/modelagem/User-Stories/US01.md, docs/modelagem/User-Stories/US02.md, docs/modelagem/User-Stories/US03.md, docs/modelagem/User-Stories/US04.md, docs/modelagem/User-Stories/US05.md, docs/modelagem/User-Stories/US06.md, docs/modelagem/User-Stories/US07.md, docs/modelagem/User-Stories/US08.md, docs/modelagem/User-Stories/US09.md, docs/modelagem/User-Stories/US10.md, docs/modelagem/backlog.md
- [ Feature] Especificação suplementar.
* Nenhum erro encontrado na documentação
=> 17 especificacao suplementar

designSprint.md, mkdocs.yml
- Documento da Design Sprint.
Documento deve ser revisado a fim de encontrar possíveis erros de português.
=> 38-DesignSprint

docs/designSprint.md, docs/diagramacausaefeito.md, docs/index.md, docs/lexicos.md, docs/mapaMental.md, docs/metodologia_do_projeto.md, docs/modelagem/priorizacao/moscow.md, docs/tap.md, mkdocs.yml
-  [Fix] ajustes em documentos e na navegação
Documentos devem esta corretos e a navegação funcionando
=> fix_documentos

docs/modelagem/backlog.md
- [Feature] Adição da coluna rastreabilidade em resultados
Sem erros de português e estrutura do markdown funcionando
=> 79-RastreabilidadeBacklog

docs/modelagem/priorizacao/moscow.md
- Refactor
- Adicionar Link nas rastreabilidades do MOSCOW
* Nenhum erro encontrado na documentação
=> 80-RastreabilidadeMOSCOW

docs/Atas/ATA_08_02_2022.md, docs/Sprints/sprint03/Planning03.md, mkdocs.yml
- Adição da Planning da sprint, e da ATA de reunião.
Ver se os links não estão quebrados, e se há algum erro de português.
=> #75 Planning and ata

docs/diagramaDeClasses.md, mkdocs.yml
- Adição do documento de diagrama de classes.
Deve estar de acorda com as normas propostas pela UML.
=> #65 Diagrama de Classes

docs/Sprints/sprint04/Review.md, mkdocs.yml
- Review da sprint
Não ter erro de português.
=> docs: add review sprint 04 #90

docs/padroes_de_projeto/grasp/baixo_acoplamento.md
Co-authored-by: Lucas Lima Ferraz <50213258+mibasFerraz@users.noreply.github.com>
- [Feature] criação do documento Baixo acoplamento (GRASP) em padrões de projeto.
Exemplo :
A pessoa responsável pela review deve verificar se o documento segue o padrão determinado pela equipe.
=> docs: Add Baixo acoplamento #110

docs/padroes_de_projeto/graps/AltaCoesao.md, mkdocs.yml
- [Feature] criação do documento alto coesão (GRASP) em padrões de projeto.
A pessoa responsável pela review deve verificar se o documento segue o padrão determinado pela equipe.
=> docs: add alta coesão #113

README.md, docs/5w2h.md, docs/Atas/ATA_18_01_2022.md, docs/Atas/ATA_24_01_2022.md, docs/DesignSprint.md, docs/DiagramaCausaEfeito.md, docs/DocumentoDeVisao.md, docs/EAP.md, docs/EspecificacaoSuplementar.md, docs/Lexicos.md, docs/ManualIdentidadeVisual.md, docs/MapaMental.md, docs/MetodologiaBPMN.md, docs/MetodologiaDoProjeto.md, docs/Personas.md, docs/PoliticaDeContribuição.md, docs/RichPicture.md, docs/TAP.md, docs/apresentacoes/Entrega1.md, docs/index.md, docs/melhorias/ENTREGA_1.md, docs/modelagem/Backlog.md, docs/modelagem/priorizacao/Moscow.md, docs/padroes_de_projeto/EMERGENTES/REST.md, docs/prototipagem/prototipoBaixa.md, docs/prototipagem/prototipoMedia.md, docs/tecnicas_elicitacao/Brainstorm.md, docs/tecnicas_elicitacao/Introspeccao.md, docs/tecnicas_elicitacao/StoryTelling.md, docs/template.md
O presente merge irá adequar o padrão de todos os documentos mencionados na entrega 1. Irá atualizar o template de documentos, adicionar links para imagens e nomes dos membros.
- Arquivos refatorados de forma homogênea( todos os documentos com todos os tópicos principais iguais) 
- Links funcionando
=> 109 Aplicar Melhorias da Primeira Entrega

docs/Sprints/sprint06/Planning06.md, mkdocs.yml
- Adição da Planning da sprint.
Ver se os links não estão quebrados, e se há algum erro de português.
=> 116: Planning sprint 06 

docs/DojoBackend.md
- [Feature] documento responsável por documentar o dojo do backend
- [Feature ] criação do documento.
A pessoa responsável pela review deve explicar através de testes (caso necessário), ou motivo lógico para o PR ser aceito.  
Exemplo:
* O documento deve conter a estrutura básica.
=> #129 dojo banckend

docs/padroes_de_projeto/GOFS/temporarios/multiton.md
`Release`, adição do Multiton do GOFS.
* Nenhum erro encontrado na documentação.
=> #127 Multiton

docs/dojoNext.md, mkdocs.yml
O documento foi criado com objetivo de documentar o que foi abordado no dojo do frontend focado na tecnologia principal, o framework NextJS
Exemplo :
=> #128 Adicionado documentacao do dojo NextJS

docs/padroes_de_projeto/GOFS/temporarios/Singleton.md
`Release`, adição do singleton do GOFS.
* Nenhum erro encontrado na documentação.
=> #126 Singleton

docs/padroes_de_projeto/GOFS/Estruturais.md
- [Feature] Criação do documento gofs bridge
Não pode ter erros.
=> #131 gofs bridge

docs/Sprints/sprint06/Review.md, mkdocs.yml
=> docs: add ReviewSprint

docs/arquitetura_reutilizacao/reutilizacao/docker.md, mkdocs.yml
- `Feature` Criação documento de reutilização de software (Docker)
=> 202 reutilizacao de software docker

docs/arquitetura_reutilizacao/das.md, mkdocs.yml
=> 211 documento arquitetura software

docs/Sprints/sprint07/Planning07.md, docs/Sprints/sprint07/Review.md, mkdocs.yml
Documentar a review  referente à sprint 7
Documento deve estar no gh-pages, e sem erro de português.
=> 204 review sprint07

docs/Sprints/sprint07/Planning07.md, mkdocs.yml
- Adição da Planning da sprint.
Ver se os links não estão quebrados, e se há algum erro de português.
=> 203 - Planning 07
